### ISSUE TITLE
download only the first video/file when there are multiple videos/files in a link

### ISSUE THREAD

**Issue by chxin579** [iyear/tdl#16]
问题：当一个链接里面有多个视频/文件的时候只下载第一个视频/文件
示例地址：https://t.me/gmtxgames/85
ps:看大佬这么整齐的英文issue，发个中文有点破坏美感了

**Comment by iyear** [comment]
It will be fixed in v0.2.0

**Comment by iyear** [comment]
@chxin579 
I will discuss the func `MessagesGetMediaGroup` with upstream lib, and it can be impled like https://github.com/pyrogram/pyrogram/blob/0dc112ea8cb0a978e39a390308cdfc9654c36a6d/pyrogram/methods/messages/get_media_group.py

The current solution is to click on the `copy link` on each single file, rather than copying the link for the entire media group.

This is not currently unresolvable, so please understand that it may not be fixed immediately.

**Comment by iyear** [comment]
The example you gave can be broken down into:
- https://t.me/gmtxgames/84
- https://t.me/gmtxgames/85
- https://t.me/gmtxgames/86
- https://t.me/gmtxgames/85
- https://t.me/gmtxgames/86
- https://t.me/gmtxgames/87
- https://t.me/gmtxgames/88
- https://t.me/gmtxgames/89

**Comment by MarshallFevi** [comment]
Will this function be looked at in the future or it won't be considered at all.

**Comment by iyear** [comment]
Essentially, the merged media files, their messages on Telegram are also independent. Passing them separately is a better choice.
