### ISSUE TITLE
Download message content as well as files

### ISSUE THREAD

**Issue by OverHash** [iyear/tdl#46]
Currently to my understanding, tdl will only download the files from chats.
Is it possible to download the message content as well for the  `tdl chat export`?

**Comment by iyear** [comment]
I thought about doing this, but I don't know if I should create a format myself or refer to tdesktop's export format

**Comment by Moberaptor** [comment]
Dear @iyear could you please add easiest (fastest) way to save messages. I'm not a Golang developer but as I could see:
https://github.com/iyear/tdl/blob/master/app/chat/export.go (line 99):
```_, err = f.WriteString(fmt.Sprintf(`{"id":%d,"type":"message","file":"0"},`, m.ID))```
Just add other fields for export.
Please could you add this feature to your brilliant program.

Kind regards.

**Comment by iyear** [comment]
@Moberaptor 
Sorry I forgot about this issue. I will add the relevant code in v0.6.1.

**Comment by Moberaptor** [comment]
@iyear could you please add this feature... Please, please, please...

**Comment by iyear** [comment]
@Moberaptor 
Maybe we need to talk about what kind of JSON you need to export to. Can you give an example?

**Comment by Moberaptor** [comment]
@iyear 
Thank you for the reply! In general it doen't matter and depends on you. I would prefer to save all data from chat, aspesially protected, with JSON or HTML and setup trigger for new messages autosave))) But I just want to download all chat (I mean with messages too) in one folder. Because I have a lot education groups in Telegram and want to save text also (it is a very important part). I mean create total backup. It means any kind of json which one will be easiear/faster for you. Many thanks!

**Comment by iyear** [comment]
Will be supported in next version

Like this, maybe we can add more fileds in the future:
```json
{
  "id": 47,
  "type": "message",
  "file": "0",
  "date": 1666001629,
  "text": "Shazam Encore v13.0.0\n@PowerAPK"
}
```

**Comment by iyear** [comment]
v0.8.0 has been released, feel free to try it or reopen the issue.

**Comment by Moberaptor** [comment]
YOU ARE BEST!!!!!!!!!!!!!!!!!
