### ISSUE TITLE
[Bug] Issue with chat ls for chat with more then 101 topics

### ISSUE THREAD

**Issue by AlphaZ19** [iyear/tdl#546]
### Describe the bug

For chat with more then 101 Topics, `tdl chat ls` only shows 101 topics, the rest are hidden.

### To Reproduce

you can try it on chat https://t.me/haijiaovideo, which ID is 1943412408

### Expected behavior

It should show all the topics, if too much for `tdl chat ls`, maybe you can make a `tdl topic ls -c CHAT` something like this.

### Version

Version: 0.16.1
Commit: bb2c69b
Date: 2024-03-01T13:21:31Z

go1.21.7 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by pgotsis** [comment]
I am facing the same problem. I have checked both table and json format. Both of them do not go over the most recently updated 101 topics.

**Comment by pgotsis** [comment]
I believe that the limitation is here:

https://github.com/iyear/tdl/blob/master/app/chat/ls.go#L231

**Comment by pgotsis** [comment]
I have looked at it a bit more and it seems that the problem is because of the ChannelsGetForumTopics. I am not 100% sure, but this API function returns topics in batches, expecting the client code to handle requesting more batches until all items have been received. I base my assumption on testing a change in line 231 (which did not work) and this discussion (https://stackoverflow.com/questions/77538243/retrieve-the-forum-topics-of-a-channel-group-in-telegram-using-wtelegramclient-a).

**Comment by XMLHexagram** [comment]
hello @iyear, I believe PR #556 fix this issue. Would you have spare time to review that PR.
