### ISSUE TITLE
When I use the tdl command to download, it will get stuck at about 12M and cannot continue./当我使用tdl命令进行下载时，会卡在12M左右无法进行下去

### ISSUE THREAD

**Issue by hcqqdctwzsz** [iyear/tdl#666]
### Describe the bug

When downloading to 12M, it will get stuck and no longer download. Sometimes it is 10M and sometimes it is 11.5M. I tried to modify the size of l, but neither 5 nor 1 helped. I saw that other people have raised this issue, but you said that adding the timeout string of characters can solve the problem, but it didn't work after I tried it. The channel has over a thousand files, and this happened when I downloaded the 200th one. No matter how much I try, I can't solve it. There is no problem with VPN, and it is very fast with other software./下载到12M的时候它会卡住不再下载，有时是10M有时是11.5M，我尝试修改l的大小，但是无论是5还是1都无济于事。我看了有其他人提出过该问题，但是您说加上timeout那一串字符能解决问题，但是我尝试后没有作用。该频道有一千多个文件，我下载到第两百个时出现该情况。不论如何尝试都无法解决，vpn是没有问题的，用其他软件速度很快。

### To Reproduce

PS D:\XX>  .\tdl -n ffhh dl -f "D:\XX\chaoduan2.json" -t 8 -s 524288 -l 1 --skip-same -d "D:\chaoduan" --reconnect-timeout 0 --continue --proxy socks5://localhost:7890
All files will be downloaded to 'D:\chaoduan' dir
CPU: 0.00% Memory: 24.59 MB Goroutines: 32
💃短(1111122222):1101 -> D:\chaoduan\1111122222_1101_1_(8~ ...  1.1% [................] [11.00 MB in 11m28.416s; ~ETA: 18h55m53s; 16.36 KB/s]
[...................................................................................] [11m28s; 16.36 KB/s]

### Expected behavior

Can operate normally. 

### Version

0.17.2

### Which OS are you running tdl on?

Windows

### Additional context

![捕获](https://github.com/iyear/tdl/assets/32481082/82630b4b-2aa2-4b0e-8fd1-83857ea056eb)

**Comment by AzureAbalone** [comment]
Yeah i got the same problem while trying to download a private channel which has 105 files. The program stuck just like you after a few files.

**Comment by iyear** [comment]
I published release [v0.17.3](https://github.com/iyear/tdl/releases/tag/v0.17.3), can you try it?

**Comment by CoolJerryy** [comment]
@iyear   I've met the same issue in release v0.17.3. The issue appeared a little bit different in this case that the download stucks intermittently for like 10~30 seconds each time and resume download for like 5 seconds. And after 5~10 minutes, an error popped up and the download stopped:

Error: group:
github. com/gotd/td/mtproto. (+Conn). Run
github. com/gotd/td@v0.105. 0/mtproto/conn. go:214
task readLoop: 
github. com/gotd/td/tdsync. (+LogGroup). Go. funcl 
github. com/gotd/td@v0.105.0/tdsync/log_group. go:48
read: 
github. com/gotd/td/mtproto. (+Conn). readLoop 
github. com/gotd/td@v0.105.0/mtproto/read, go:193
read: 
github. com/gotd/td/transport. (* connection). Recv 
github. com/gotd/td@v0.105.0/transport/connection. go:70
read intermediate: 
github. com/gotd/td/proto/codec. Intermediate. Read 
github. com/gotd/tdev0.105. 0/proto/codec/intermediate. go:73
read length:
github. com/gotd/td/proto/codec. readLen github. com/gotd/td@v0.105.0/proto/codec/codec. go:35
EOF

Thinking of it might be due to a network error so I used "chat ls" command right after the issue occurs and found it took a few more seconds to list the channels than usual, as if the network had temporarily dropped out. After that, I used "chat ls" again and it started to list channels in a normal amount of time.
