### ISSUE TITLE
Bug - When Telegram files have the same name the program stops with an error

### ISSUE THREAD

**Issue by art435** [iyear/tdl#71]
I tried to download some files that have the same name (duplicates) in Telegram channel. But the program stops with this error
`callback: rename downloads\January Session.rtf.tmp downloads\January Session.rtf.rtf: The process cannot access the file because it is being used by another process.`

**Comment by iyear** [comment]
Sorry I'm replying now because I've been busy recently.

Yes, this problem exists. What do you think is the best way to solve it?

1. Add random strings to file name: the file name may be too long
2. Skip if files have the same name: some files with the same name may be missed

**Comment by art435** [comment]
The program should offer 2 options to users.
1. Don't download new files that have identical names. Fast but with small risks.
2. Download the new files in a separate folder, calculate the hashes, and delete if they are the same.

This should be done real time, and the download should continue for other files.
See [here](https://github.com/iyear/tdl/issues/75#issuecomment-1355746173).

**Comment by art435** [comment]
This issue is fixed from version 0.6.0

**Comment by iyear** [comment]
Is it possible to modify the file name template to achieve no duplication?

**Comment by art435** [comment]
To prevent this issue? How? My template for file name is `{{ .FileName }}`, just the filename.

**Comment by iyear** [comment]
Is it acceptable to add some random string after the file name?

**Comment by art435** [comment]
This solution doesn't interfere with the deduplication? If the file name in source chat is abc.flac and is renamed abc1.flac, and later tries to download an identical file abc.flac, it won't find the duplicate in chat because the file name has changed. abc.flac is now abc1.flac

**Comment by rsyqvthv** [comment]
same issue here with `Version: 0.7.2`

not sure if this is actually means file name duplicate, as the error shows "file is being used by another process."
would ending the process will solve the issue?

as I use template `{{.MessageDate}}-{{.FileName}}` when downloading, 
I don't think the destination file name will be duplicated, 
as by the file system limitation, uploader won't able to upload duplicated file in a very same time.

**Comment by locvez** [comment]
> This solution doesn't interfere with the deduplication? If the file name in source chat is abc.flac and is renamed abc1.flac, and later tries to download an identical file abc.flac, it won't find the duplicate in chat because the file name has changed. abc.flac is now abc1.flac

Yes, it would, because abc.flac already exists, abc.flac is downloaded again (with diff. file saize) it is renamed abc1.flac, both files now exist. If another abc.flac is downloaded, with a different file size, it would be renamed abc2.flac. This means abc.flac, abc1.flac and abc2.flac all exist with different file sizes.

**Comment by WinstReedr** [comment]
Hi everyone, I'm not a programmer, but this bug destroyed half a year of my work. I'm asking for your help. There was a document in the favorites chat, let's call it document B. I left it there as a backup. Then, for 4 months, I edited this file on my phone. When the work was done, I decided to drop the finished document A in the same chat. But its size was displayed incorrectly. I opened document A and it turned out to be document B. I deleted the message and repeated it. The result is the same. I reached into the file directory already on my phone, and my document A was replaced with document B. These documents have the same name but different size. I know it's a big mistake to make such a rare backup, and I admit this mistake. I have tried various file recovery programs, they have not yielded results. There is no recovery point on the phone. I'm just hoping that my document A is cached somewhere or something. Can you tell me how to find the document, if it still exists?
